### ISSUE TITLE
Error Under 1.5.0

### ISSUE THREAD

**Issue by mwweb** [joomlatools/joomlatools-vagrant#112]
I have joomlatools box running fine with 1.4.4, and attempted to upgrade this evening to 1.5.0, and now I can't even get Joomlatools box up and running. Please see the below error:

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o rw,tcp,nolock,noacl,async,uid=1000,gid=1000 var_www /var/www

The error output from the command was:

  fmask     =<arg> umask of regular files

**Comment by stevenrombauts** [comment]
@mwweb Sorry to hear you're having trouble with the upgrade. It's very hard for us to tell what could be going wrong as this is very specific to your machine. A mount issue mostly points to two things: a mismatch in [Virtualbox Guest Additions](https://www.virtualbox.org/manual/ch04.html) versions or your host machine that fails to run the NFS service (due to firewall or misconfiguration)

To rule out the guest additions we recommend you run the new 1.5 box on the latest versions of Vagrant (2.0) and Virtualbox (5.1). These versions are working fine for us.

I've added this to the [Requirements](https://github.com/joomlatools/joomlatools-vagrant#requirements) in the readme just now.

Finally, we ask you to not post Vagrant related questions as an Issue but instead get in touch via [chat or forum](https://github.com/joomlatools/joomlatools-vagrant#reporting-issues). Thanks!

**Comment by stevenrombauts** [comment]
@mwweb We're continuing this discussion at https://groups.google.com/d/msg/joomlatools-dev/H70XolJqMB0/VeIyy2nYAAAJ
