### ISSUE TITLE
Ad vbguest as a default plugin

### ISSUE THREAD

**Issue by tonypartridge** [joomlatools/joomlatools-vagrant#119]
It would be good if you could include vbguest as a default plugin so the guest additions always match that of the host.

**Comment by stevenrombauts** [comment]
Agreed @tonypartridge that would be a good idea. We're automatically installing the vagrant-triggers plugin already so we could just as well add vagrant-vbguest.

**Comment by tonypartridge** [comment]
Exactly :-) Whilst we are on this... maybe even letsencrypt ;-)

**Comment by stevenrombauts** [comment]
We have decided to revert this change as it has some severe implications. First of all, we received some reports where the plugin installation fails because of broken bundler dependencies on different operating systems. If installation fails, it could prevent you from starting up the box at all.

Secondly, it's a global plugin that will change other boxes on your system as well, potentially breaking them. 

We'll leave this up to the user whether or not to install this plugin and add some more info to the FAQ.
