### ISSUE TITLE
joomla site:create mysite not able to connect MySql

### ISSUE THREAD

**Issue by sajalaspl** [joomlatools/joomlatools-vagrant#122]
### Describe your environment

  * OS: Ubuntu 17
  * Joomlatools Vagrant version: latest

### Describe the problem:
Seems to be issue with the Mysql.

$ joomla site:create mysite
Downloading https://github.com/joomla/joomla-cms/archive/3.8.7.tar.gz - this could take a few minutes ..
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")

#### Steps to reproduce:

  1. _____
  2. _____

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by stevenrombauts** [comment]
@sajalaspl As our [ticket template](https://raw.githubusercontent.com/joomlatools/joomlatools-vagrant/master/.github/issue_template.md) mentions at the top, we request that you refer to our [Gitter](http://gitter.im/joomlatools/dev) chat or [mailing list](https://groups.google.com/forum/#!forum/joomlatools-dev) for these types of questions first.

That being said, it looks like MySQL went away, so you can try to restart MySQL with this:

```
sudo service mysql stop
sudo service mysql start
```

and see if that gives you any clues as to what might be going on.

We also ran into a similar issue recently which was being caused by the background updater script being started multiple times (#121). Killing all php processes or just rebooting the box will sort it out (temporarily)
