### ISSUE TITLE
can't download joomla staging in PHP 7

### ISSUE THREAD

**Issue by javigomez** [joomlatools/joomlatools-vagrant#22]
Using PHP 5.5 in the Joomla box there are no issues downloading specific releases of joomla:

![Uploading Screen Shot 2016-03-08 at 15.30.00.png…]()

However I have switched to PHP 7 

![screen shot 2016-03-08 at 15 31 45](https://cloud.githubusercontent.com/assets/1375475/13604448/f960fb72-e542-11e5-8c5d-2fbe9c499c3d.png)

And I have noticed this error raises:

![screen shot 2016-03-08 at 14 02 50](https://cloud.githubusercontent.com/assets/1375475/13604464/0bca8a6c-e543-11e5-95a3-90f1e936137f.png)

**Comment by stevenrombauts** [comment]
It looks like stream wrappers are now enabling peer verification by default when using SSL/TLS [since PHP 5.6](https://secure.php.net/manual/en/migration56.openssl.php). The compiled version doesn't know where to look for the certificates bundle so it can't verify GitHub's SSL certificate. This also means that the same issue will occur if you build a new 5.6.x version on the box. 

To remedy this on your box, correct the path to the CA bundle:

```
box php:ini openssl.cafile /etc/ssl/certs/ca-certificates.crt
box php:ini openssl.capath /usr/lib/ssl/
```

You can verify if the paths are correctly set by looking out the cafile and capath values in the output from `php -r 'print_r(openssl_get_cert_locations());'`.

That should do it. We'll need to fix this in a next release of the box by automatically setting these paths after building. 

Thanks for the report @javigomez! Please let me know if the above workaround solves the issue on your current machine.

**Comment by javigomez** [comment]
I can confirm that your commands fixes the issue.

Thanks very much ^_^
