### ISSUE TITLE
Mailcatcher not working

### ISSUE THREAD

**Issue by greenleafmedia** [joomlatools/joomlatools-vagrant#23]
Hi there -

I have a fresh install of the vagrant box.  I set my Joomla 3.5.0 admin to SMTP host 127.0.0.1 and set the port to 1025.  When I send the test email in Joomla config area it spits back the following error in the admin: 

```
Test mail could not be sent.

Could not instantiate mail function.
```

On the command line I try to test mailcatcher using: `echo "Subject: test" | /home/vagrant/.rvm/gems/ruby-2.2.1/bin/catchmail -v me@domain.com` and I get back `catchmail: version unknown`.

Any ideas why I can't get mail to work?

**Comment by stevenrombauts** [comment]
Hi @greenleafmedia,

I tested this real quick with a Joomla 3.5.0 sites created using the `joomla site:create testsite` command and its working just fine on my end.

Is the MailCatcher interface accessible at [http://joomla.box:1080/](http://joomla.box:1080/)? If not, make sure it's started with `sudo service mailcatcher start`. 

The cli command to send a mail through `catchmail` throws that error because it doesn't know the `-v` argument. The following command runs successfully on my box:

`echo "Subject: test" | /home/vagrant/.rvm/gems/ruby-2.2.1/bin/catchmail -f me@joomla.box -t foo@bar.com`

Does that command work for you?

**Comment by greenleafmedia** [comment]
Hi @stevenrombauts  -

Thanks for the reply.  I tried your CLI test and it was worked for that test.  Just to make sure I wasn't going crazy, I installed a fresh Joomla `joomla site:create test --release=latest` and tested again.  I'm still getting the error out of the box.  I've even destroyed my vagrant box and built it up again.

So, we now know that mailcatcher seems to be working fine.  Seems like Joomla can't connect properly to it though through SMTP.  Destroying the box and bringing it up again should have fixed everything, right?  Any other ideas for troubleshooting?

**Comment by stevenrombauts** [comment]
I'm not sure what to try next. Have you tried installing an older Joomla version to see if that made a difference? Example:  `joomla site:create joomla336 --release=3.3.6`.

Is mailcatcher listening on the right port? What's the output of `sudo lsof -i :1025`? 

Also, does it work if you stop the service (`sudo service mailcatcher stop`) and then run it yourself with `ruby /home/vagrant/.rvm/gems/ruby-2.2.4/bin/mailcatcher`?

**Comment by greenleafmedia** [comment]
I think I've found it.  In the newer Joomla versions there is a "Send Test Mail" button at the bottom of mail settings config that was giving me the error (still does).  However, if I try to send an actual message using the messaging component it does go through.  So, I seems to be some bug with the "Send Test Mail" function in the configuration.  Now I know to not test using the test button. :)

Thanks for the troubleshooting.

**Comment by stevenrombauts** [comment]
Confirmed. The `test mail` button doesn't work for me either. Regular contact form still works as it should be. Thanks!
