### ISSUE TITLE
php7 & xdebug

### ISSUE THREAD

**Issue by marcodings** [joomlatools/joomlatools-vagrant#90]
When i setup for php7 the box xdebug:enable command does not seem to do anything.
It says it disables / enables but xdebug is not shown in php_info.

**Comment by stevenrombauts** [comment]
Hi @marcodings, thanks for reporting and welcome! We have explicitly skipped installing xdebug for PHP 7 because we were unable to make it work properly at the time. (see [34a14b3](https://github.com/joomlatools/joomlatools-vagrant/commit/34a14b31f1c37253f29f1d8b1b042c6fcbd55251#diff-d1e664c955e4759384b2a67c380f4769R280)

We will get back to this and see if we can fix it in a next release.

**Comment by marcodings** [comment]
Thanks for getting back. I have been  using the combination successfully over the last months, so I'm confident it will work.

**Comment by stevenrombauts** [comment]
@marcodings This [small code change](https://github.com/joomlatools/joomlatools-vagrant/commit/309feb7f56ebfda7c4311a4b715aa7797273ba61) is all that is needed to have the script build xdebug in PHP 7.x versions. You can apply this in `/home/vagrant/phpmanager/phpmanager` file already if you need it now. 

Quick note, we are reconsidering the way we manage different PHP versions. Possibly by removing the build script entirely and install each minor version by default. We'll see what works best. :)
